<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="gantry" params="
    parent
    long_rail_length
    long_rail_width
    long_rail_offset
    small_rail_length
    small_rail_width
    rail_height
    rail_thickness
    torso_height
    initial_positions">

    <!-- ROS2 Control -->
    <xacro:include filename="$(find ariac_description)/urdf/ceiling_robot/gantry.ros2_control.xacro"/>
    <xacro:gantry_ros2_control
      name="gantry"
      initial_positions="${initial_positions}"
    />

    <!--Information on the rails-->
    <link name='long_rail_1'>
      <collision>
        <origin xyz="${-small_rail_length / 2 + long_rail_width / 2} ${long_rail_offset} ${rail_height}" rpy="0 0 0"/>
        <geometry>
          <box size="${long_rail_width} ${long_rail_length} ${rail_thickness}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="${-small_rail_length / 2 + long_rail_width / 2} ${long_rail_offset} ${rail_height}" rpy="0 0 0"/>
        <geometry>
          <box size="${long_rail_width} ${long_rail_length} ${rail_thickness}"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia
            ixx="1" ixy="0.0" ixz="0.0"
            iyy="1" iyz="0.0"
            izz="1"/>
      </inertial>
    </link>

    <gazebo reference="long_rail_1">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <joint name="rail_1_world" type="fixed">
      <parent link="${parent}"/>
      <child link="long_rail_1"/>
      <origin xyz="-2.0 0.0 0.0" rpy="0.0 0.0 ${-pi/2}"/>
    </joint>

    <!-- Link long_rail_2 -->
    <link name='long_rail_2'>
      <collision>
        <origin xyz="${small_rail_length / 2 - long_rail_width / 2} ${long_rail_offset} ${rail_height}" rpy="0 0 0"/>
        <geometry>
          <box size="${long_rail_width} ${long_rail_length} ${rail_thickness}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="${small_rail_length / 2 - long_rail_width / 2} ${long_rail_offset} ${rail_height}" rpy="0 0 0"/>
        <geometry>
          <box size="${long_rail_width} ${long_rail_length} ${rail_thickness}"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia
            ixx="1" ixy="0.0" ixz="0.0"
            iyy="1" iyz="0.0"
            izz="1"/>
      </inertial>
    </link>
      
    <gazebo reference="long_rail_2">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <joint name="rail_2_rail_1" type="fixed">
      <parent link="long_rail_1"/>
      <child link="long_rail_2"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name='small_rail'>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${small_rail_width} ${small_rail_length} ${rail_thickness}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${small_rail_width} ${small_rail_length} ${rail_thickness}"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia
            ixx=".1" ixy="0.0" ixz="0.0"
            iyy="1" iyz="0.0"
            izz=".1"/>
      </inertial>
    </link>
      
    <gazebo reference="small_rail">
      <material>Gazebo/GreyTransparent</material>
    </gazebo>

    <joint name="gantry_x_axis_joint" type="prismatic">
      <parent link="long_rail_2"/>
      <child link="small_rail"/>
      <origin xyz="0.0 -5.0 ${rail_height + rail_thickness}" rpy="0.0 0.0 ${pi/2}"/>
      <axis xyz="1 0 0"/>
      <limit lower="${-long_rail_length / 2 + small_rail_width / 2}"
          upper="${long_rail_length / 2 - small_rail_width / 2}"
          velocity="1"
          effort="100000"/>
    </joint>
    
    <link name="torso_base">
      <visual>
        <geometry>
          <mesh filename="file://$(find ariac_description)/meshes/gantry/torso_base.dae" scale="2 2 2"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="file://$(find ariac_description)/meshes/gantry/torso_base.dae" scale="2 2 2"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia
            ixx=".1" ixy="0.0" ixz="0.0"
            iyy="1" iyz="0.0"
            izz=".1"/>
      </inertial>
    </link>

    <gazebo reference="torso_base">
      <material>Gazebo/FlatBlack</material>
      <selfCollide>1</selfCollide>
    </gazebo>

    <joint name="gantry_y_axis_joint" type="prismatic">
      <parent link="small_rail"/>
      <child link="torso_base"/>
      <origin xyz="0 0 ${torso_height}" rpy="${pi} ${pi} ${pi/2}"/>
      <axis xyz="1 0 0"/>
      <!--Add a 0.5m buffer for joint limits to avoid self-collisions-->
      <limit lower="${-small_rail_length / 2 + .5}"
        upper="${small_rail_length / 2 - .5}"
        velocity="1"
        effort="100000"/>
    </joint>

    <link name="torso_main">
      <visual>
        <geometry>
          <mesh filename="file://$(find ariac_description)/meshes/gantry/torso_fixed_normals.dae" scale="2 2 2"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="file://$(find ariac_description)/meshes/gantry/torso_fixed_normals.dae" scale="2 2 2"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia
          ixx=".1" ixy="0.0" ixz="0.0"
          iyy="1" iyz="0.0"
          izz=".1"/>
      </inertial>
      
      <gazebo>
        <material>
          <script>
            <uri>file://media/materials/scripts/gazebo.material</uri>
            <name>Gazebo/Grey</name>
          </script>
        </material>
      </gazebo>
    </link>

    <gazebo reference="torso_main">
      <selfCollide>1</selfCollide>
    </gazebo>

    <joint name="gantry_rotation_joint" type="revolute">
      <parent link="torso_base"/>
      <child link="torso_main"/>
      <origin xyz="0 0 0" rpy="${pi} ${pi} 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-2 * pi}"
        upper="${2 * pi}"
        velocity="${pi/4}"
        effort="100000"/>
    </joint>
    
    <link name="torso_tray">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find ariac_description)/meshes/gantry/gantry_tray.dae" scale="0.5 0.5 1.2"/>
        </geometry>
      </visual>
      <collision name="torso_tray_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find ariac_description)/meshes/gantry/gantry_tray.dae" scale="0.5 0.5 1.2"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia
          ixx="0.0408" ixy="0.0" ixz="0.0"
          iyy="0.02084" iyz="0.0"
          izz="0.0616"/>
      </inertial>
    </link>

    <!-- We have to make this a non-fixed joint otherwise it is not recofnized by Gazebo -->
    <!-- The limit will not allow the joint to move -->
    <joint name="gantry_tray_joint" type="revolute">
      <parent link="torso_main"/>
      <child link="torso_tray"/>
      <origin xyz="-0.017851 0.0 0.637444" rpy="0 0 ${pi/2}"/>
      <axis xyz="0 0 1"/>
      <limit velocity="6.5" effort="1000" lower="0" upper="0" />
    </joint>

  </xacro:macro>
</robot>