sensors:
  # breakbeam_0:
  #   visualize_fov: false
  #   type: break_beam
  #   pose:
  #     xyz: [-0.35, 3, 0.95]
  #     rpy: [0, 0, pi]

  # proximity_sensor_0:
  #   type: proximity_sensor
  #   pose:
  #     xyz: [-0.573, 2.84, 1]
  #     rpy: [pi/2, pi/6, pi/2]

  # laser_profiler_0:
  #   type: laser_profiler
  #   pose:
  #     xyz: [-0.573, 1.486, 1.526]
  #     rpy: [pi/2, pi/2, 0]

  right_bins_camera:
    type: rgbd_camera
    visualize_fov: false
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  # left_bins_depth_camera:
  #   type: depth_camera
  #   visualize_fov: false
  #   pose:
  #     xyz: [-2.286, -2.96, 1.8]
  #     rpy: [pi, pi/2, 0]

  # right_bins_logical_camera:
  #   visualize_fov: false
  #   type: logical_camera
  #   pose:
  #     xyz: [-2.286, 2.96, 1.8]
  #     rpy: [pi, pi/2, 0]

  # left_bins_logical_camera:
  #   visualize_fov: false
  #   type: logical_camera
  #   pose:
  #     xyz: [-2.286, -2.96, 1.8]
  #     rpy: [pi, pi/2, 0]
  