agv4/controller_manager:
  ros__parameters:

    update_rate: 60 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
agv4/velocity_controller:
  ros__parameters:
    joints:
      - agv4_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position