agv1/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController



agv2/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController



agv3/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController



agv4/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController



agv1/velocity_controller:
  ros__parameters:
    joints:
      - agv1_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position



agv2/velocity_controller:
  ros__parameters:
    joints:
      - agv2_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position



agv3/velocity_controller:
  ros__parameters:
    joints:
      - agv3_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position



agv4/velocity_controller:
  ros__parameters:
    joints:
      - agv4_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position