agv1/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    

agv1/agv_controller:
  ros__parameters:
    joints:
      - agv_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      agv_joint: {trajectory: 0.1, goal: 0.1}


agv2/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    

agv2/agv_controller:
  ros__parameters:
    joints:
      - agv_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      agv_joint: {trajectory: 0.1, goal: 0.1}


agv3/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    

agv3/agv_controller:
  ros__parameters:
    joints:
      - agv_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      agv_joint: {trajectory: 0.1, goal: 0.1}


agv4/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    

agv4/agv_controller:
  ros__parameters:
    joints:
      - agv_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      agv_joint: {trajectory: 0.1, goal: 0.1}


