controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    ariac_robots_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    floor_robot_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ceiling_robot_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


ceiling_robot_joint_trajectory_controller:
  ros__parameters:
    joints:
      - small_long_joint
      - torso_rail_joint
      - torso_base_main_joint
      - ceiling_shoulder_pan_joint
      - ceiling_shoulder_lift_joint
      - ceiling_elbow_joint
      - ceiling_wrist_1_joint
      - ceiling_wrist_2_joint
      - ceiling_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      small_long_joint: {trajectory: 0.1, goal: 0.1}
      torso_rail_joint:  {trajectory: 0.1, goal: 0.1}
      torso_base_main_joint: {trajectory: 0.1, goal: 0.1}
      ceiling_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ceiling_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ceiling_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ceiling_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ceiling_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ceiling_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }



floor_robot_joint_trajectory_controller:
  ros__parameters:
    joints:
      - linear_actuator
      - floor_shoulder_pan_joint
      - floor_shoulder_lift_joint
      - floor_elbow_joint
      - floor_wrist_1_joint
      - floor_wrist_2_joint
      - floor_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      linear_actuator: {trajectory: 0.1, goal: 0.1}
      floor_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      floor_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      floor_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      floor_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      floor_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      floor_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
