# Trial Name: sample.yaml
# ARIAC2023
# 2022-11-04 13:48:00

# ENVIRONMENT SETUP

time_limit: 400 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [1, 2, 3] 
  slots: [2, 3, 5]

parts:
  agvs:
    agv4:
      tray_id: 0
      parts:
        - type: 'pump'
          color: 'green'
          quadrant: 1
          rotation: 0
          flipped: true
        - type: 'sensor'
          color: 'green'
          quadrant: 3
          rotation: 'pi'
  
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1: 
      - type: 'pump'
        color: 'red'
        slots: [1, 5, 9]
        rotation: 'pi/6'
    bin3:
      - type: 'regulator'
        color: 'purple'
        slots: [2, 3]
        rotation: 'pi/6'
        flipped: false
    bin6:
      - type: 'battery'
        color: 'blue'
        slots: [1, 3, 5, 7]
        rotation: 'pi/3'
        flipped: false
        faulty: [3, 7]
      - type: 'battery'
        color: 'green'
        slots: [8, 9]
        rotation: 0
        flipped: true
    bin8:
      - type: 'sensor'
        color: 'orange'
        slots: [1, 2, 3, 4, 5, 6, 7, 8, 9]

  conveyor_belt: # population params for conveyor belt
    active: true
    spawn_rate: 3.0 # seconds between spawn
    order: 'sequential' # random or sequential
    parts_to_spawn:
      - type: 'battery'
        color: 'red'
        number: 5
        offset: 0.5 # between -1 and 1
        flipped: false
        rotation: 'pi/6'
      - type: 'sensor'
        color: 'green'
        number: 5
        offset: -0.25 # between -1 and 1
        flipped: true
        rotation: 'pi'
        
# GLOBAL CHALLENGES
challenges:
  - dropped_part:
      robot: 'ceiling_robot'
      type: 'battery'
      color: 'green'
      drop_after: 1 # drops the 2nd part the robot successfully picks
      delay: 2 # drops after 2 seconds
  - dropped_part:
      robot: 'floor_robot'
      type: 'sensor'
      color: 'purple'
      drop_after: 2 # drops the 3nd part the robot successfully picks
      delay: 3 # drops after 2 seconds
  - human:
      behavior: 'antagonistic'
      time_condition: 10.0
  # - robot_malfunction:
  #     duration: 20.0
  #     robots_to_disable: ['floor_robot']
  #     time_condition: 10.0
  # - robot_malfunction:
  #     duration: 20.0
  #     robots_to_disable: ['floor_robot']
  #     time_condition: 225.0
  # - robot_malfunction:
  #     duration: 25.0
  #     robots_to_disable: ['ceiling_robot']
  #     submission_condition:
  #       order_id: 'MMB30H56'
  # - robot_malfunction:
  #     duration: 5.0
  #     robots_to_disable: ['floor_robot','ceiling_robot']
  #     part_place_condition:
  #       color: 'green'
  #       type: 'sensor'
  #       agv: 4
  - sensor_blackout:
      duration: 5.0
      sensors_to_disable: ['break_beam']
      time_condition: 20
  - sensor_blackout:
      duration: 5.0
      sensors_to_disable: ['lidar', 'logical_camera']
      submission_condition:
        order_id: 'MMB30H57'
      # time_condition: 20
      # part_place_condition:
      #   type: 'sensor'
      #   color: 'green'
      #   agv: 2
  - faulty_part:
      order_id: 'MMB30H56'
      quadrant1: true
      quadrant2: true
  - faulty_part:
      order_id: 'MMB30H00'
      quadrant1: true
      

# ORDER SETUP

orders:
  - id: 'MMB30H00'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 0
      destination: 'warehouse'
      products:
        - type: 'pump'
          color: 'green'
          quadrant: 1
        - type: 'sensor'
          color: 'green'
          quadrant: 3
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 10
    priority: false
    kitting_task:
      agv_number: 2
      tray_id: 2
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 1
        - type: 'sensor'
          color: 'red'
          quadrant: 2
        - type: 'regulator'
          color: 'purple'
          quadrant: 3
        - type: 'pump'
          color: 'orange'
          quadrant: 4
  - id: 'MMB30H57'
    type: 'assembly'
    # announcement:
    #   submission_condition:
    #     order_id: 'MMB30H56'
    announcement:
      time_condition: 5
    priority: false
    assembly_task:
      agv_number: [4,3]
      station: 'as4'
      products:
        - type: 'sensor'
          color: 'green'
          assembled_pose: # relative to breifcase frame
            xyz: [0.405, 0.164, 0.110]
            rpy: ['pi/2', 0, 0]
          assembly_direction: [-1, 0, 0] # unit vector in briefcase frame
        - type: 'battery'
          color: 'red'
          assembled_pose: # relative to breifcase frame
            xyz: [0.12, 0.122, 0.1222]
            rpy: ['pi/4', 0, 0]
          assembly_direction: [-1, -1.1, -1.11] # unit vector in briefcase frame
        - type: 'regulator'
          color: 'purple'
          assembled_pose: # relative to breifcase frame
            xyz: [0.13, 0.133, 0.133]
            rpy: ['pi', 0, 0]
          assembly_direction: [-2, -2.2, -2.22] # unit vector in briefcase frame
        - type: 'pump'
          color: 'orange'
          assembled_pose: # relative to breifcase frame
            xyz: [0.14, 0.144, 0.144]
            rpy: [0.2, 0, 0]
          assembly_direction: [-3, -3.3, -3.33] # unit vector in briefcase frame
  - id: 'MMB30H58'
    type: 'combined'
    # announcement:
    #   time_condition: 20
    announcement:
      submission_condition:
        order_id: 'MMB30H57'
    priority: false
    combined_task:
      station: 'as4'
      products:
        - type: 'sensor'
          color: 'green'
          assembled_pose: # relative to breifcase frame
            xyz: [0.405, 0.164, 0.110]
            rpy: ['pi/2', 0, 0]
          assembly_direction: [-1, 0, 0] # unit vector in briefcase frame
  # - id: '1X7K29EV'
  #   type: 'assembly'
  #   announcement:
  #     part_place_condition:
  #       color: 'green'
  #       type: 'sensor'
  #       agv: 4
  #   priority: true
  #   assembly_task:
  #     agv_number: [4]
  #     station: 'as4'
  #     products:
  #       - type: 'sensor'
  #         color: 'green'
  #         assembled_pose: # relative to breifcase frame
  #           xyz: [0.405, 0.164, 0.110]
  #           rpy: ['pi/2', 0, 0]
  #         assembly_direction: [-1, 0, 0] # unit vector in briefcase frame
  # - id: '2Y7K29EV'
  #   type: 'combined'
  #   announcement:
  #     submission_condition:
  #       order_id: '1X7K29EV'
  #   priority: false
  #   combined_task:
  #     station: 'as2'
  #     products:
  #       - type: 'sensor'
  #         color: 'blue'
  #         assembled_pose: # relative to briefcase frame
  #           xyz: [0.405, 0.164, 0.110]
  #           rpy: ['pi/2', 0, 0]
  #         assembly_direction: [-1, 0, 0] # unit vector in briefcase frame
  # # - id: 'MMB30G34'
  # #   type: 'combined'
  # #   announcement_time: 0
  # #   priority: false
  # #   challenges:
  # #   kitting_task:
  # #     agv_number: 1
  # #     tray_id: 6
  # #     destination: 'as2'
  # #     products:
  # #       - type: 'pump'
  # #         color: 'red'
  # #         quadrant: 3
  # #   assembly_task:
  # #     agv_number: 1
  # #     station: 'as2'
  # #     products:
  # #       - type: 'pump'
  # #         color: 'red'
  # #         assembled_pose: # relative to breifcase frame
  # #           xyz: [0.032, -0.153, 0.076]
  # #           rpy: [0, 0, 0]
  # #         assembly_direction: [0, 0, -1] # unit vector in breifcase frame