# Trial Name: qc.yaml
# ARIAC2023

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [3, 8] 
  slots: [1, 4]

parts:  
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2:
      - type: 'pump'
        color: 'purple'
        slots: [1, 3, 7, 9]
        flipped: true
    bin6:
      - type: 'battery'
        color: 'blue'
        slots: [1, 3, 7, 9]
  agvs:
    agv4:
      tray_id: 3
      parts:
        - type: 'battery'
          color: 'blue'
          quadrant: 1
          rotation: 0
          flipped: true

  conveyor_belt: # population params for conveyor belt
    active: false


# challenges:
#   - faulty_part:
#       order_id: 'MMB30H56'
#       quadrant1: true


orders:
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 1
        # - type: 'pump'
        #   color: 'purple'
        #   quadrant: 3
  - id: '8EX92YUD'
    type: 'kitting'
    announcement:
      time_condition: 30
    priority: false
    kitting_task:
      agv_number: 1
      tray_id: 8
      destination: 'warehouse'
      products:
        # - type: 'battery'
        #   color: 'blue'
        #   quadrant: 4
        - type: 'pump'
          color: 'purple'
          quadrant: 2