# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - floor_robot_controller
    - floor_arm_controller
    - ceiling_robot_controller
    - ceiling_arm_controller
    - gantry_controller

  floor_robot_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - linear_actuator
      - floor_shoulder_pan_joint
      - floor_shoulder_lift_joint
      - floor_elbow_joint
      - floor_wrist_1_joint
      - floor_wrist_2_joint
      - floor_wrist_3_joint
  floor_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - floor_shoulder_pan_joint
      - floor_shoulder_lift_joint
      - floor_elbow_joint
      - floor_wrist_1_joint
      - floor_wrist_2_joint
      - floor_wrist_3_joint
  ceiling_robot_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - small_long_joint
      - torso_rail_joint
      - torso_base_main_joint
      - ceiling_shoulder_pan_joint
      - ceiling_shoulder_lift_joint
      - ceiling_elbow_joint
      - ceiling_wrist_1_joint
      - ceiling_wrist_2_joint
      - ceiling_wrist_3_joint
  ceiling_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ceiling_shoulder_pan_joint
      - ceiling_shoulder_lift_joint
      - ceiling_elbow_joint
      - ceiling_wrist_1_joint
      - ceiling_wrist_2_joint
      - ceiling_wrist_3_joint
  gantry_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - small_long_joint
      - torso_rail_joint
      - torso_base_main_joint